### ISSUE TITLE
Style TableOptions 

### ISSUE THREAD

**Issue by smaraghi** [CSIS-iLab/tech-policy-database#19]
#### Description
TableOptions is the container component that holds the search feature, collections filter, custom filter, text resize buttons, and table scroll buttons. These features need to be aligned according to mock-up styling.

#### Tasks
- [ ] Position features into the same line 

#### Additional Information
In order to complete this task, classNames must be added to the following components: SearchFilter, CustomFilter and CollectionsFilter, with consideration for future implementation of the TableScroll component

**Comment by jnschrag** [comment]
I'm going to close this in favor of creating individual issues per component.
