### ISSUE TITLE
Table Search Error

### ISSUE THREAD

**Issue by smaraghi** [CSIS-iLab/tech-policy-database#37]
#### Description
When a user searches for incorrect or non-existing data, a new table appears with an error message

#### Tasks
- [ ] Construct error table as div
- [x] Style as signified in mock up

**Comment by jnschrag** [comment]
I don't think this needs to be it's own table, but rather a part of the existing table. I would recommend creating this as a single table cell rather than a div. Something like this:

```html
<table>
  <thead></thead>
  <tbody>
    <tr><td colspan="# of Columns">Error message goes here</td></tr>
  </tbody>
</table>
```
